# Generated by Django 4.0.3 on 2022-04-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegoria',
            new_name='Categoria',
        ),
    ]
