# Generated by Django 4.0.4 on 2022-04-15 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estadovotacion_facultad_tipovotacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('semestreActual', models.IntegerField(null=True)),
                ('idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.facultad')),
            ],
        ),
    ]
