# Generated by Django 4.0.4 on 2022-04-15 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='votacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estadovotacion')),
                ('idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.facultad')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipovotacion')),
            ],
        ),
    ]
