# Generated by Django 4.0.4 on 2022-04-15 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_votacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
                ('propuesta', models.CharField(max_length=45)),
                ('idEstudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.estudiante')),
                ('idVotacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.votacion')),
            ],
        ),
    ]
