# Generated by Django 4.0.4 on 2022-04-15 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decano',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idFacultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.facultad')),
            ],
        ),
    ]
