# Generated by Django 4.0.4 on 2022-04-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_categoria_delete_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decano',
            name='user',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
    ]
