# Generated by Django 4.0.4 on 2022-04-22 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_alter_decano_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decano',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decano', to=settings.AUTH_USER_MODEL),
        ),
    ]
