# Generated by Django 4.0.4 on 2022-05-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_votacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_votaciones', to='app.tipovotacion'),
        ),
    ]
