from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('index/', views.index, name='index'), 
    path('categorias', views.categorias, name='categorias'), 
    path('categorias/<int:id>/', views.categoria, name='categoria'), 
    path('peliculas/', views.peliculas, name='peliculas'), 
    path('menu_decano/', views.menu_decano, name='menu_decano'), 
    path('cambiar_estado/', views.cambiar_estado, name='cambiar_estado'), 
    path('candidatos_ganadores/', views.candidatos_ganadores, name='candidatos_ganadores'), 
    path('candidatos_ganadores2/', views.candidatos_ganadores2, name='candidatos_ganadores2'), 
    path('consult_candidatos_es/', views.consult_candidatos_es, name='consult_candidatos_es'), 
    path('consult_candidatos/', views.consult_candidatos, name='consult_candidatos'), 
    path('consult_estudiante/', views.consult_estudiante, name='consult_estudiante'), 
    path('consult/', views.consult, name='consult'), 
    path('consulta_votacionfacultad/', views.consulta_votacionfacultad, name='consulta_votacionfacultad'), 
    path('consultar_votacionsemestre/', views.consultar_votacionsemestre, name='consultar_votacionsemestre'), 
    path('consultar_mivoto/', views.consultar_mivoto, name='consultar_mivoto'), 
    path('crear_estudiante/', views.crear_estudiante, name='crear_estudiante'), 
    path('crear_votacion/', views.crear_votacion, name='crear_votacion'), 
    path('est/', views.est, name='est'), 
    path('hacer_votacion/', views.hacer_votacion, name='hacer_votacion'), 
    path('hacervotacion_facultad/', views.hacervotacion_facultad, name='hacervotacion_facultad'), 
    path('ingresar/', views.ingresar, name='ingresar'), 
    path('lista_estudiantes/', views.lista_estudiantes, name='lista_estudiantes'), 
    path('listade_votaciones_est/', views.listade_votaciones_est, name='listade_votaciones_est'), 
    path('listade_votaciones/', views.listade_votaciones, name='listade_votaciones'), 
    path('listadecandidatos_vot/', views.listadecandidatos_vot, name='listadecandidatos_vot'), 
    path('Menu_estudiante/', views.Menu_estudiante, name='Menu_estudiante'), 
    path('postularestudiante/', views.postularestudiante, name='postularestudiante'), 
    path('postularse/', views.postularse, name='postularse'), 
    path('Resultados_finales/', views.Resultados_finales, name='Resultados_finales'), 
    path('resultadosfinales_estudiantes/', views.resultadosfinales_estudiantes, name='resultadosfinales_estudiantes'), 
    path('Ustedse_postulo/', views.Ustedse_postulo, name='Ustedse_postulo'), 
    path('Vot/', views.Vot, name='Vot'), 
    path('votacion_creada/', views.votacion_creada, name='votacion_creada'), 
    path('voto_realizado/', views.voto_realizado, name='voto_realizado'), 
]